// Route + POI data. Photo URLs are stable Picsum seeds — swap with real
// Sa Blava coastal photography in production. Coordinates are approximate
// hand-tuned around Aiguablava.

const img = (seed, w = 800, h = 450) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

const POIS_CALES = [
  {
    id: "cala-fonda",
    type: "cala",
    typeIcon: "🏖",
    minutesFromStart: 35,
    coords: [3.218, 41.9335],
    depthM: 4,
    shade: "migdia",
    snorkel: 4,
    accessibility: "kayak",
    name: {
      ca: "Cala Fonda",
      es: "Cala Fonda",
      en: "Cala Fonda",
      fr: "Cala Fonda",
    },
    description: {
      ca: "Una cala de fons sorrós amb aigües cristal·lines i parets de pedra calcària que cauen suaument fins als 4 metres. Aparcat el caiac sobre la sorra, fa de bon endinsar-se a nedar. Pinedes ofereixen ombra a partir de migdia.",
      es: "Una cala de fondo arenoso con aguas cristalinas y paredes calcáreas que descienden suavemente hasta los 4 metros. Aparca el kayak en la arena y date un baño. Las pinedas ofrecen sombra a partir del mediodía.",
      en: "A sandy-bottomed cove with crystalline water and limestone walls dropping gently to 4m. Beach the kayak on the sand and dive in. Pines provide shade from noon.",
      fr: "Une crique au fond sablonneux avec une eau cristalline et des parois calcaires descendant doucement jusqu'à 4m. Pose le kayak sur le sable et baigne-toi. Les pins font de l'ombre dès midi.",
    },
    images: [img("cala-fonda-1"), img("cala-fonda-2"), img("cala-fonda-3")],
  },
  {
    id: "cova-pirates",
    type: "cova",
    typeIcon: "🕳",
    minutesFromStart: 50,
    coords: [3.2208, 41.9337],
    depthM: 6,
    shade: "tot el dia",
    snorkel: 5,
    accessibility: "kayak",
    name: {
      ca: "Cova dels Pirates",
      es: "Cueva de los Piratas",
      en: "Pirates' Cave",
      fr: "Grotte des Pirates",
    },
    description: {
      ca: "Una cova marina de 18 metres de fondària amb sostre baix i aigua maragda dins. Entra a poc a poc i mantén el caiac al centre del túnel. Vigila amb les onades a la boca de la cova.",
      es: "Una cueva marina de 18 metros de profundidad con techo bajo y agua esmeralda. Entra despacio y mantén el kayak en el centro del túnel. Cuidado con el oleaje a la entrada.",
      en: "A 18-metre sea cave with low ceiling and emerald water inside. Enter slowly and keep the kayak centered. Watch the swell at the entrance.",
      fr: "Une grotte marine de 18 mètres au plafond bas et à l'eau émeraude. Entre doucement, garde le kayak au centre. Attention à la houle à l'entrée.",
    },
    images: [img("cova-pirates-1"), img("cova-pirates-2")],
  },
  {
    id: "platja-raco",
    type: "platja",
    typeIcon: "🏖",
    minutesFromStart: 70,
    coords: [3.2238, 41.9341],
    depthM: 2,
    shade: "matí",
    snorkel: 3,
    accessibility: "kayak,peu",
    name: {
      ca: "Platja del Racó",
      es: "Playa del Rincón",
      en: "Racó Beach",
      fr: "Plage du Racó",
    },
    description: {
      ca: "Petita platja de sorra fina arrecerada del vent de tramuntana. Lloc ideal per fer una pausa, treure el caiac a terra i prendre un mos. Accessible també a peu pel camí de ronda.",
      es: "Pequeña playa de arena fina resguardada de la tramontana. Ideal para una pausa, sacar el kayak y comer algo. Accesible también a pie por el camino de ronda.",
      en: "Small fine-sand beach sheltered from the tramontana wind. Perfect for a break — beach the kayak and have a snack. Also reachable on foot via the coastal path.",
      fr: "Petite plage de sable fin abritée de la tramontane. Parfait pour une pause — sors le kayak et casse la croûte. Accessible aussi à pied par le chemin côtier.",
    },
    images: [img("platja-raco-1"), img("platja-raco-2"), img("platja-raco-3")],
  },
  {
    id: "snorkel-cap-blanc",
    type: "snorkel",
    typeIcon: "🤿",
    minutesFromStart: 90,
    coords: [3.2268, 41.9345],
    depthM: 8,
    shade: "tarda",
    snorkel: 5,
    accessibility: "kayak",
    name: {
      ca: "Punt de Snorkel Cap Blanc",
      es: "Punto de Snorkel Cap Blanc",
      en: "Cap Blanc Snorkel Spot",
      fr: "Spot de Snorkeling Cap Blanc",
    },
    description: {
      ca: "Un dels millors punts de snorkel del litoral d'Aiguablava. Visibilitat habitualment superior a 8 metres. Esculls de Posidònia, sargs i daurades. Amarra el caiac al rocam i salta amb les ulleres posades.",
      es: "Uno de los mejores puntos de snorkel del litoral. Visibilidad habitual superior a 8 metros. Praderas de Posidonia, sargos y doradas. Amarra el kayak a la roca y salta con las gafas puestas.",
      en: "One of the best snorkel spots on the Aiguablava coast. Visibility typically over 8 metres. Posidonia meadows, white seabream, gilthead. Tie up to the rock and jump in.",
      fr: "L'un des meilleurs spots de snorkeling de la côte. Visibilité souvent supérieure à 8m. Prairies de posidonies, sars et dorades. Amarre le kayak au rocher et plonge.",
    },
    images: [
      img("snorkel-cap-blanc-1"),
      img("snorkel-cap-blanc-2"),
      img("snorkel-cap-blanc-3"),
    ],
  },
  {
    id: "mirador-freus",
    type: "mirador",
    typeIcon: "👁",
    minutesFromStart: 105,
    coords: [3.229, 41.9349],
    depthM: 12,
    shade: "no",
    snorkel: 2,
    accessibility: "kayak",
    name: {
      ca: "Mirador dels Freus",
      es: "Mirador dels Freus",
      en: "Freus Viewpoint",
      fr: "Belvédère dels Freus",
    },
    description: {
      ca: "Punt panoràmic amb vistes a les illes Medes en dies clars. Fons de 12 metres just sota el caiac. No hi ha lloc per amarrar — manté't en moviment i gaudeix del paisatge.",
      es: "Punto panorámico con vistas a las Islas Medes en días claros. 12 metros de fondo justo bajo el kayak. No hay lugar de amarre — mantente en movimiento.",
      en: "Panoramic point with views of the Medes Islands on clear days. 12m depth right below. No mooring — stay moving and enjoy the view.",
      fr: "Point panoramique avec vue sur les Îles Medes par temps clair. 12m de fond. Pas d'amarrage — reste en mouvement.",
    },
    images: [img("mirador-freus-1"), img("mirador-freus-2")],
  },
  {
    id: "port-aiguablava",
    type: "port",
    typeIcon: "⚓",
    minutesFromStart: 120,
    coords: [3.2155, 41.9326],
    depthM: 3,
    shade: "tarda",
    snorkel: 1,
    accessibility: "kayak,peu,cotxe",
    name: {
      ca: "Port d'Aiguablava",
      es: "Puerto de Aiguablava",
      en: "Aiguablava Port",
      fr: "Port d'Aiguablava",
    },
    description: {
      ca: "Tornada al moll de Sa Blava. Aigües calmes i poc fondes per acabar la jornada. Recorda retornar el caiac al lloc d'origen i avisar el monitor.",
      es: "Vuelta al muelle de Sa Blava. Aguas calmas y poco profundas para terminar la jornada. Recuerda devolver el kayak al lugar de origen.",
      en: "Back at the Sa Blava jetty. Calm shallow water to finish the trip. Return the kayak to its original spot and check in with the guide.",
      fr: "Retour au ponton de Sa Blava. Eaux calmes et peu profondes pour terminer. Remets le kayak à sa place et préviens le moniteur.",
    },
    images: [img("port-aiguablava-1"), img("port-aiguablava-2")],
  },
];

const POIS_PENYA = [
  {
    id: "far-aiguablava",
    type: "mirador",
    typeIcon: "🗼",
    minutesFromStart: 25,
    coords: [3.217, 41.9298],
    depthM: 7,
    shade: "no",
    snorkel: 3,
    accessibility: "kayak",
    name: {
      ca: "Far d'Aiguablava",
      es: "Faro de Aiguablava",
      en: "Aiguablava Lighthouse",
      fr: "Phare d'Aiguablava",
    },
    description: {
      ca: "El far d'Aiguablava domina el cap des de 35 metres d'alçada. Vista en picat sobre el caiac — moment ideal per fer una foto.",
      es: "El faro domina el cabo desde 35 metros de altura. Vista en picado sobre el kayak — momento ideal para una foto.",
      en: "The lighthouse stands 35m above the cape. Dramatic view down to the kayak — prime photo moment.",
      fr: "Le phare domine le cap à 35m. Vue plongeante sur le kayak — moment photo idéal.",
    },
    images: [img("far-aiguablava-1"), img("far-aiguablava-2")],
  },
  {
    id: "penya-cap-blanc",
    type: "penya",
    typeIcon: "🪨",
    minutesFromStart: 60,
    coords: [3.219, 41.9268],
    depthM: 18,
    shade: "matí",
    snorkel: 4,
    accessibility: "kayak",
    name: {
      ca: "Penya-segats de Cap Blanc",
      es: "Acantilados de Cap Blanc",
      en: "Cap Blanc Cliffs",
      fr: "Falaises du Cap Blanc",
    },
    description: {
      ca: "Els penya-segats de Cap Blanc cauen 60 metres fins al mar. Pala suau i mantén distància de 8 metres a la paret — hi ha desprenirments ocasionals.",
      es: "Los acantilados de Cap Blanc caen 60 metros hasta el mar. Palada suave y mantén 8m de distancia — hay desprendimientos ocasionales.",
      en: "The Cap Blanc cliffs drop 60m to the sea. Easy paddling, keep 8m off the wall — occasional rockfall.",
      fr: "Les falaises du Cap Blanc plongent à 60m. Pagaie souple, garde 8m de distance — chutes de pierres occasionnelles.",
    },
    images: [img("penya-cap-blanc-1"), img("penya-cap-blanc-2")],
  },
  {
    id: "tres-forats",
    type: "cova",
    typeIcon: "🕳",
    minutesFromStart: 95,
    coords: [3.2212, 41.9239],
    depthM: 9,
    shade: "tot el dia",
    snorkel: 5,
    accessibility: "kayak",
    name: {
      ca: "Cova dels Tres Forats",
      es: "Cueva de los Tres Agujeros",
      en: "Three Holes Cave",
      fr: "Grotte des Trois Trous",
    },
    description: {
      ca: "Tres entrades naturals il·luminen una cambra interior de 12 metres d'amplada. Llum blava espectacular cap a les 11 del matí. Entra només amb mar plana.",
      es: "Tres entradas naturales iluminan una cámara de 12 metros. Luz azul espectacular hacia las 11 de la mañana. Entrar solo con mar en calma.",
      en: "Three natural openings light up a 12m chamber. Spectacular blue light around 11am. Only enter on flat sea.",
      fr: "Trois ouvertures naturelles illuminent une chambre de 12m. Lumière bleue spectaculaire vers 11h. Entrer uniquement par mer calme.",
    },
    images: [
      img("tres-forats-1"),
      img("tres-forats-2"),
      img("tres-forats-3"),
      img("tres-forats-4"),
    ],
  },
  {
    id: "cala-aiguafreda",
    type: "cala",
    typeIcon: "🏖",
    minutesFromStart: 130,
    coords: [3.2238, 41.9213],
    depthM: 3,
    shade: "matí",
    snorkel: 4,
    accessibility: "kayak,peu",
    name: {
      ca: "Cala Aiguafreda",
      es: "Cala Aiguafreda",
      en: "Aiguafreda Cove",
      fr: "Crique d'Aiguafreda",
    },
    description: {
      ca: "Cala recòndita de pedres rodones i aigua glacial — d'aquí el nom. Pausa obligada a meitat de la ruta. Hi ha una font d'aigua dolça al penya-segat est.",
      es: "Cala recóndita de cantos rodados y agua helada — de ahí el nombre. Parada obligada a mitad de la ruta. Hay una fuente de agua dulce en el acantilado este.",
      en: "Hidden cove with rounded pebbles and ice-cold water — hence the name. A must-stop midway. Freshwater spring on the eastern cliff.",
      fr: "Crique cachée aux galets ronds et eau glacée — d'où le nom. Halte obligatoire. Source d'eau douce sur la falaise est.",
    },
    images: [img("cala-aiguafreda-1"), img("cala-aiguafreda-2")],
  },
  {
    id: "cap-de-begur",
    type: "mirador",
    typeIcon: "👁",
    minutesFromStart: 165,
    coords: [3.2262, 41.9201],
    depthM: 22,
    shade: "no",
    snorkel: 2,
    accessibility: "kayak",
    name: {
      ca: "Cap de Begur",
      es: "Cap de Begur",
      en: "Cap de Begur",
      fr: "Cap de Begur",
    },
    description: {
      ca: "El punt més extrem de la ruta. Mar oberta cap a llevant. Tomba i torna cap al moll — el viatge de tornada té el vent a favor en general.",
      es: "El punto más extremo de la ruta. Mar abierta al este. Da la vuelta — el viaje de regreso suele tener viento a favor.",
      en: "The furthest point. Open sea to the east. Turn back — the return leg usually has tailwind.",
      fr: "Le point le plus éloigné. Mer ouverte vers l'est. Demi-tour — le retour est généralement vent arrière.",
    },
    images: [img("cap-de-begur-1"), img("cap-de-begur-2")],
  },
];

const POIS_FAMILIAR = [
  {
    id: "punta-hort",
    type: "mirador",
    typeIcon: "👁",
    minutesFromStart: 12,
    coords: [3.2135, 41.932],
    depthM: 3,
    shade: "tot el dia",
    snorkel: 3,
    accessibility: "kayak",
    name: {
      ca: "Punta de l'Hort",
      es: "Punta de l'Hort",
      en: "Punta de l'Hort",
      fr: "Punta de l'Hort",
    },
    description: {
      ca: "Petit promontori amb vistes obertes a la badia. Aigua poc profunda, ideal per a nens. Hi ha bancs de peix petit just a la base.",
      es: "Pequeño promontorio con vistas a la bahía. Agua poco profunda, ideal para niños. Bancos de peces pequeños en la base.",
      en: "A small promontory with bay views. Shallow, perfect for kids. Schools of small fish at the base.",
      fr: "Petit promontoire avec vue sur la baie. Eau peu profonde, parfait pour les enfants. Bancs de petits poissons à la base.",
    },
    images: [img("punta-hort-1"), img("punta-hort-2")],
  },
  {
    id: "cala-petita",
    type: "cala",
    typeIcon: "🏖",
    minutesFromStart: 25,
    coords: [3.2118, 41.9308],
    depthM: 1.5,
    shade: "tarda",
    snorkel: 3,
    accessibility: "kayak,peu",
    name: {
      ca: "Cala Petita",
      es: "Cala Petita",
      en: "Cala Petita",
      fr: "Cala Petita",
    },
    description: {
      ca: "Cala diminuta amb un metre i mig d'aigua sobre sorra blanca. Perfecta per fer un bany amb la família i deixar el caiac al rocam.",
      es: "Cala diminuta con metro y medio de agua sobre arena blanca. Perfecta para un baño en familia y dejar el kayak en la roca.",
      en: "Tiny cove with 1.5m of water over white sand. Perfect for a family swim — beach the kayak on the rocks.",
      fr: "Crique minuscule avec 1,5m d'eau sur sable blanc. Parfait pour une baignade en famille — kayak sur les rochers.",
    },
    images: [img("cala-petita-1"), img("cala-petita-2"), img("cala-petita-3")],
  },
  {
    id: "roca-pi",
    type: "mirador",
    typeIcon: "🌲",
    minutesFromStart: 45,
    coords: [3.2152, 41.9304],
    depthM: 4,
    shade: "tot el dia",
    snorkel: 4,
    accessibility: "kayak",
    name: {
      ca: "Roca del Pi",
      es: "Roca del Pino",
      en: "Pine Rock",
      fr: "Rocher du Pin",
    },
    description: {
      ca: "Una roca solitària amb un pi creixent al seu cim, gairebé tocant l'aigua. Punt fotogràfic de tota la ruta. La tornada al moll és just a 5 minuts.",
      es: "Una roca solitaria con un pino creciendo en la cima, casi tocando el agua. Punto fotográfico clave. La vuelta al muelle está a 5 minutos.",
      en: "A lone rock with a pine growing at the top, almost touching the water. Signature photo spot. Five minutes back to the jetty.",
      fr: "Un rocher solitaire avec un pin au sommet, presque dans l'eau. Point photo emblématique. 5 min du ponton.",
    },
    images: [img("roca-pi-1"), img("roca-pi-2")],
  },
];

export const ROUTES = [
  {
    id: "cales",
    name: {
      ca: "Ruta de les Cales",
      es: "Ruta de las Calas",
      en: "Coves Route",
      fr: "Route des Criques",
    },
    tagline: {
      ca: "De la platja a les coves de Cap Blanc.",
      es: "De la playa a las cuevas de Cap Blanc.",
      en: "From the beach to the Cap Blanc sea caves.",
      fr: "De la plage aux grottes du Cap Blanc.",
    },
    description: {
      ca: "Endinsa't a les cales amagades del litoral d'Aiguablava, des de la platja del moll fins a les coves marines de Cap Blanc. Aigües tranquil·les, parets de pedra calcària i pinedes que arriben fins al mar. La ruta més emblemàtica de Sa Blava.",
      es: "Adéntrate en las calas escondidas del litoral de Aiguablava, desde la playa del muelle hasta las cuevas marinas de Cap Blanc. La ruta más emblemática de Sa Blava.",
      en: "Slip into the hidden coves of Aiguablava, from the jetty beach to the Cap Blanc sea caves. Calm water, limestone walls, pines down to the sea. Sa Blava's signature route.",
      fr: "Plonge-toi dans les criques cachées d'Aiguablava, jusqu'aux grottes marines du Cap Blanc. La route emblématique de Sa Blava.",
    },
    color: "#0B6E8C",
    distanceKm: 4.2,
    durationHours: 2,
    difficulty: "medium",
    conditions: {
      // wind speed in knots, wave height in metres
      wind: { ok: 12, caution: 18 },
      wave: { ok: 0.5, caution: 0.8 },
    },
    poiCount: POIS_CALES.length,
    image: img("aiguablava-cales-hero", 800, 480),
    cardImage: img("aiguablava-cales-card", 560, 340),
    pois: POIS_CALES,
    geometry: [
      [3.2155, 41.9326],
      [3.2178, 41.9333],
      [3.2208, 41.9337],
      [3.2238, 41.9341],
      [3.2268, 41.9345],
      [3.229, 41.9349],
    ],
  },
  {
    id: "penya-segats",
    name: {
      ca: "Ruta dels Penya-segats",
      es: "Ruta de los Acantilados",
      en: "Cliffs Route",
      fr: "Route des Falaises",
    },
    tagline: {
      ca: "Imponents penya-segats del Cap de Begur.",
      es: "Imponentes acantilados del Cap de Begur.",
      en: "Towering cliffs of Cap de Begur.",
      fr: "Falaises imposantes du Cap de Begur.",
    },
    description: {
      ca: "Una aventura pels penya-segats de Cap Blanc fins al Cap de Begur. Parets de 60 metres, coves marines i punts de snorkel excepcionals. Per a paladors experimentats — vigila el vent de gregal.",
      es: "Una aventura por los acantilados de Cap Blanc hasta Cap de Begur. Paredes de 60m, cuevas marinas y snorkel excepcional. Para palistas experimentados.",
      en: "An adventure along the Cap Blanc cliffs to Cap de Begur. 60m walls, sea caves and exceptional snorkel. For experienced paddlers — watch the gregal wind.",
      fr: "Une aventure le long des falaises du Cap Blanc jusqu'au Cap de Begur. Parois de 60m, grottes et snorkel exceptionnel. Pour pagayeurs expérimentés.",
    },
    color: "#FF8C6B",
    distanceKm: 6.8,
    durationHours: 3.5,
    difficulty: "hard",
    conditions: {
      wind: { ok: 10, caution: 15 },
      wave: { ok: 0.4, caution: 0.7 },
    },
    poiCount: POIS_PENYA.length,
    image: img("aiguablava-cliffs-hero", 800, 480),
    cardImage: img("aiguablava-cliffs-card", 560, 340),
    pois: POIS_PENYA,
    geometry: [
      [3.2155, 41.9326],
      [3.217, 41.9298],
      [3.219, 41.9268],
      [3.2212, 41.9239],
      [3.2238, 41.9213],
      [3.2262, 41.9201],
    ],
  },
  {
    id: "familiar",
    name: {
      ca: "Ruta Familiar",
      es: "Ruta Familiar",
      en: "Family Route",
      fr: "Route Famille",
    },
    tagline: {
      ca: "Aigües tranquil·les, ideal per a famílies.",
      es: "Aguas tranquilas, ideal para familias.",
      en: "Calm waters, perfect for families.",
      fr: "Eaux calmes, parfait en famille.",
    },
    description: {
      ca: "La ruta ideal per a famílies i principiants. Aigües tranquil·les, cales accessibles i un parell d'aturades fotogràfiques. Sortida directa del moll, sense vent de fora.",
      es: "Ruta ideal para familias y principiantes. Aguas tranquilas, calas accesibles y paradas fotográficas. Sin viento de fuera.",
      en: "Ideal for families and beginners. Calm water, accessible coves, two or three photo stops. Sheltered from offshore wind.",
      fr: "Idéal pour les familles et les débutants. Eaux calmes, criques accessibles, arrêts photos. À l'abri du vent du large.",
    },
    color: "#4A9B72",
    distanceKm: 2.1,
    durationHours: 1,
    difficulty: "easy",
    conditions: {
      wind: { ok: 15, caution: 22 },
      wave: { ok: 0.7, caution: 1.0 },
    },
    poiCount: POIS_FAMILIAR.length,
    image: img("aiguablava-family-hero", 800, 480),
    cardImage: img("aiguablava-family-card", 560, 340),
    pois: POIS_FAMILIAR,
    geometry: [
      [3.2155, 41.9326],
      [3.2135, 41.932],
      [3.2118, 41.9308],
      [3.2122, 41.9295],
      [3.2138, 41.9292],
      [3.2152, 41.9304],
    ],
  },
];

export function findRoute(id) {
  return ROUTES.find((r) => r.id === id);
}

export const MARINA = {
  name: "Sa Blava — Moll d'Aiguablava",
  coords: [3.2155, 41.9326],
};
